<?php
// --- MARCH 14: END OF DAY SETTLEMENT ---
session_start();
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}
require_once 'db_connect.php';

// 1. Fetch Today's Date
$today = date('Y-m-d');

// 2. Summary Statistics for Today
$stmt = $pdo->prepare("SELECT 
    COUNT(id) as total_transactions, 
    SUM(total_price) as total_cash,
    SUM(quantity) as total_items
    FROM sales 
    WHERE DATE(sale_date) = ?");
$stmt->execute([$today]);
$summary = $stmt->fetch();

// 3. Itemized Breakdown for Today
$stmt = $pdo->prepare("SELECT s.*, p.name 
    FROM sales s 
    JOIN products p ON s.product_id = p.id 
    WHERE DATE(s.sale_date) = ? 
    ORDER BY s.sale_date DESC");
$stmt->execute([$today]);
$daily_sales = $stmt->fetchAll();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily Close - <?php echo $today; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8fafc; font-family: 'Inter', sans-serif; }
        .report-header { background: #1e293b; color: white; padding: 40px 0; border-radius: 0 0 25px 25px; }
        .card { border: none; border-radius: 15px; }
        .stat-val { font-size: 1.8rem; font-weight: 800; }
        @media print { .no-print { display: none; } body { background: white; } }
    </style>
</head>
<body>

<div class="report-header text-center mb-5 shadow">
    <h1 class="fw-800">DAILY CLOSE REPORT</h1>
    <p class="opacity-75">Date: <?php echo date('D, M j, Y'); ?></p>
    <div class="no-print mt-3">
        <button onclick="window.print()" class="btn btn-light fw-bold px-4">🖨️ Print Summary</button>
        <a href="dashboard.php" class="btn btn-outline-light px-4">Back to Dashboard</a>
    </div>
</div>

<div class="container">
    <div class="row g-4 mb-5">
        <div class="col-md-4">
            <div class="card shadow-sm p-4 text-center">
                <div class="text-muted small fw-bold mb-1 uppercase">TOTAL CASH IN</div>
                <div class="stat-val text-success"><?php echo number_format($summary['total_cash'] ?? 0); ?> /=</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm p-4 text-center">
                <div class="text-muted small fw-bold mb-1 uppercase">TRANSACTIONS</div>
                <div class="stat-val"><?php echo $summary['total_transactions']; ?></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm p-4 text-center">
                <div class="text-muted small fw-bold mb-1 uppercase">ITEMS SOLD</div>
                <div class="stat-val"><?php echo $summary['total_items'] ?? 0; ?></div>
            </div>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header bg-white py-3">
            <h5 class="mb-0 fw-bold">Today's Sales Audit Log</h5>
        </div>
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th class="ps-4">Time</th>
                        <th>Product</th>
                        <th>Qty</th>
                        <th class="text-end pe-4">Total</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (count($daily_sales) > 0): ?>
                        <?php foreach($daily_sales as $sale): ?>
                        <tr>
                            <td class="ps-4 text-muted"><?php echo date('H:i', strtotime($sale['sale_date'])); ?></td>
                            <td class="fw-bold"><?php echo htmlspecialchars($sale['name']); ?></td>
                            <td><?php echo $sale['quantity']; ?></td>
                            <td class="text-end pe-4 fw-bold"><?php echo number_format($sale['total_price']); ?> /=</td>
                        </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <tr><td colspan="4" class="text-center py-5">No sales recorded today.</td></tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="mt-5 text-center text-muted small pb-5">
        Report Generated By: <?php echo $_SESSION['username']; ?> | Time: <?php echo date('H:i:s'); ?>
    </div>
</div>

</body>
</html>d