<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily Close - {{ $today }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8fafc; font-family: 'Inter', sans-serif; }
        .report-header { background: #1e293b; color: white; padding: 40px 0; border-radius: 0 0 25px 25px; }
        .card { border: none; border-radius: 15px; }
        .stat-val { font-size: 1.8rem; font-weight: 800; }
        @media print { .no-print { display: none; } body { background: white; } }
    </style>
</head>
<body>

<div class="report-header text-center mb-5 shadow">
    <h1 class="fw-800">DAILY CLOSE REPORT</h1>
    <p class="opacity-75">Date: {{ now()->format('D, M j, Y') }}</p>
    <div class="no-print mt-3">
        <button onclick="window.print()" class="btn btn-light fw-bold px-4">🖨️ Print Summary</button>
        <a href="{{ route('dashboard') }}" class="btn btn-outline-light px-4">Back to Dashboard</a>
    </div>
</div>

<div class="container">
    <div class="row g-4 mb-5">
        <div class="col-md-4">
            <div class="card shadow-sm p-4 text-center">
                <div class="text-muted small fw-bold mb-1 text-uppercase">Total Cash In</div>
                <div class="stat-val text-success">{{ number_format($summary['total_cash']) }} /=</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm p-4 text-center">
                <div class="text-muted small fw-bold mb-1 text-uppercase">Transactions</div>
                <div class="stat-val">{{ $summary['total_transactions'] }}</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow-sm p-4 text-center">
                <div class="text-muted small fw-bold mb-1 text-uppercase">Items Sold</div>
                <div class="stat-val">{{ $summary['total_items'] }}</div>
            </div>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header bg-white py-3">
            <h5 class="mb-0 fw-bold">Today's Sales Audit Log</h5>
        </div>
        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light">
                    <tr>
                        <th class="ps-4">Time</th>
                        <th>Product</th>
                        <th>Qty</th>
                        <th class="text-end pe-4">Total</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($dailySales as $sale)
                        <tr>
                            <td class="ps-4 text-muted">{{ $sale->sale_date->format('H:i') }}</td>
                            <td class="fw-bold">{{ $sale->product_name }}</td>
                            <td>{{ $sale->quantity }}</td>
                            <td class="text-end pe-4 fw-bold">{{ number_format((float) $sale->total_price) }} /=</td>
                        </tr>
                    @empty
                        <tr><td colspan="4" class="text-center py-5">No sales recorded today.</td></tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <div class="mt-5 text-center text-muted small pb-5">
        Report Generated By: {{ auth()->user()->username }} | Time: {{ now()->format('H:i:s') }}
    </div>
</div>

</body>
</html>
